//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBetweenUs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLike
    {
        public int LikeID { get; set; }
        public int PostID { get; set; }
        public int AccountID { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblPost tblPost { get; set; }
    }
}
