//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBetweenUs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPost()
        {
            this.tblLikes = new HashSet<tblLike>();
        }
    
        public int PostID { get; set; }
        public int AccountID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PostTime { get; set; }
        public Nullable<int> LikesNumber { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLike> tblLikes { get; set; }
    }
}
