//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfBetweenUs.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequest
    {
        public int RequestID { get; set; }
        public int SenderAccountID { get; set; }
        public int ReciverAccountID { get; set; }
        public Nullable<bool> Accepted { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblAccount tblAccount1 { get; set; }
    }
}
